steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/tms-planning:${COMMIT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['create', '--name', 'img', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/tms-planning:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/tms-planning:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'img:/tms-planning/api_descriptor.pb', 'api_descriptor.pb']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', '-h', 'Cache-Control: public, max-age=86400', 'cp', 'api_descriptor.pb', 'gs://gobolt-toolbox/tms-planning/endpoints/${COMMIT_SHA}.pb']

- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'img:/tms-planning/dist/tms-planning-1.0.tar.gz', 'tms-planning-${SHORT_SHA}.tar.gz']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', '-h', 'Cache-Control: public, max-age=86400', 'cp', 'tms-planning-${SHORT_SHA}.tar.gz', 'gs://gobolt-toolbox/tms-planning/dist/tms-planning-${SHORT_SHA}.tar.gz']


timeout: 300s