steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/route-planner:${COMMIT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['create', '--name', 'img', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/route-planner:${COMMIT_SHA}']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/bitbucket.org/gobolt_team/route-planner:${COMMIT_SHA}']

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['cp', 'img:/route-planner/api_descriptor.pb', 'api_descriptor.pb']
#
#- name: 'gcr.io/cloud-builders/gsutil'
#  args: ['-m', '-h', 'Cache-Control: public, max-age=86400', 'cp', 'api_descriptor.pb', 'gs://gobolt-toolbox/route-planner/endpoints/${COMMIT_SHA}.pb']

- name: 'gcr.io/cloud-builders/docker'
  args: ['cp', 'img:/route-planner/dist/route-planner-1.0.tar.gz', 'route-planner-${SHORT_SHA}.tar.gz']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', '-h', 'Cache-Control: public, max-age=86400', 'cp', 'route-planner-${SHORT_SHA}.tar.gz', 'gs://gobolt-toolbox/route-planner/dist/route-planner-${SHORT_SHA}.tar.gz']

- name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
  args:
    - '-Dsonar.host.url=https://sonar.gobolt.in'
    - '-Dsonar.login=67938b6373fffadf0083ec6be6650a54cd06a1a4'
    - '-Dsonar.projectKey=route-planner-beta'
    - '-Dsonar.organization=gobolt_team'
    - '-Dsonar.sources=.'

timeout: 300s