import { createTypes } from 'reduxsauce';


export default createTypes<any>(`
  OPEN_DRAWER
  OPEN_SUB_DRAWER
  SHOW_LOADER
  HIDE_LOADER
  SHOW_ALERT
  HIDE_ALERT
  DISABLE_ACTION_BUTTON
  ENABLE_ACTION_BUTTON
  CITY_LIST
  STATE_LIST
  VEHICLE_TYPE_LIST
  TRACKING_ASSETS_LIST
  LOCATION_LIST
  DEVICE_DATA_LIST
  TRACKING_VENDOR_LIST
  ROLE_LIST
  PERMISSION_LIST
  USER_INFO
  SET_COUNT_NOTIFICATION
  REFRESH_COUNT
  OK_PRESSED
  SIDE_NAVIGATION
  MAIN_MENU_INFO
  INVOICE_FILTER
  REMOVE_INVOICE_FILTER
  TOGGLE_MODAL
  POLL_START
  POLL_STOP
`);