import { createTypes } from 'reduxsauce';


export default createTypes<any>(`
    SHOW_LOADING
    HIDE_LOADING
    USER_PARAMS
    CLEAR_USER_PARAMS
    SET_FREIGHT_TYPE
    ORIGIN_SUGGESTION
    DESTINATION_SUGGESTION
    PARTNER_LIST
    LANE_LIST
    AUTO_SELECT
    SET_ERROR
    TOGGLE_MODAL
    TOGGLE_ORDER_DETAILS
    SAVE_SHIPMENT_DETAILS
    REMOVE_SHIPMENT_DETAILS
    ADD_SHIPMENT_DETAILS
    TOGGLE_BULK_UPLOAD
    CLEAR_SHIPMENT_DETAILS
    ADD_MULTIPLE_SHIPMENT_DETAILS
`);