import { createTypes } from 'reduxsauce';


export default createTypes<any>(`
    TOGGLE_FILTER
    TOGGLE_MODAL
    SELECTED_ELEMENT
    SET_RESPONSE
    SET_CURRENT_PAGE
    REFRESH_LIST
    SEARCH_QUERY
    SET_ROW_PER_PAGE
    SHOW_LOADING
    HIDE_LOADING
    USER_FILTER
    REMOVE_FILTER
    TOGGLE_POINTS_MODAL
    SET_DEFAULT_EXPAND_ROW_INDEX
    REFRESH_PERIODIC_LIST
    SET_ORDER_DETAILS
`);