import { createTypes } from 'reduxsauce'

export default createTypes<any>(`
    TOGGLE_FILTER
    SELECTED_ELEMENT
    SET_RESPONSE
    REFRESH_LIST
    SEARCH_QUERY
    SET_CURRENT_PAGE
    SET_ROW_PER_PAGE
    TOGGLE_POINTS_MODAL
    USER_FILTER
    REMOVE_FILTER
    TOGGLE_MODAL
    SHOW_LOADING
    HIDE_LOADING
`);