import { createTypes } from 'reduxsauce';

export default createTypes<any>(`
    TOGGLE_FILTER
    TOGGLE_MODAL
    SELECTED_ELEMENT
    SET_RESPONSE
    SET_CURRENT_PAGE
    REFRESH_LIST
    SEARCH_QUERY
    SET_ROW_PER_PAGE
    SHOW_LOADING
    HIDE_LOADING
    USER_FILTER
    REMOVE_FILTER
    SELECTED_INDEX
    TOGGLE_POINTS_MODAL
    SET_INITIAL_VALUE
    SET_CHECKED_RESPONSE
    REFRESH_PERIODIC_LIST
    SET_DEFAULT_EXPAND_ROW_INDEX
    SET_SHOW_SUBMIT_BUTTON
`);