import { createTypes } from 'reduxsauce';


export default createTypes<any>(`
    TOGGLE_FILTER
    TOGGLE_MODAL
    TOGGLE_CANCEL_MODAL
    SELECTED_ELEMENT
    SET_RESPONSE
    SET_CURRENT_PAGE
    SET_ROW_PER_PAGE
    TOGGLE_POINTS_MODAL
    USER_FILTER
    REMOVE_FILTER
    REFRESH_LIST
    SHOW_LOADING
    HIDE_LOADING
    TOGGLE_BULK_UPLOAD
`);