import { createTypes } from 'reduxsauce'


export default createTypes<any>(`
    TOGGLE_FILTER
    TOGGLE_MODAL
    SELECTED_ELEMENT
    SET_RESPONSE
    SET_CURRENT_PAGE
    SET_ROW_PER_PAGE
    REMOVE_FILTER
    JOB_LISTING_FILTER
    SHOW_LOADING
    HIDE_LOADING
    TOGGLE_POINTS_MODAL
    TOGGLE_PLANNING_MODAL
    REFRESH_LIST
`);