export interface LocationTypeState {
    selectedItem: EnableLocationDetails | undefined,
    pagination: any,
    listData: Array<EnableLocationDetails> | undefined,
    openModal: boolean,
    refreshList: boolean,
    loading: boolean,
    currentPage: number,
    pageSize: number,
    searchQuery: string,
    filterParams: any,
    filterChips: any,
}

export interface EnableLocationDetails {
    latitude: number,
    longitude: number,
    cityName: string,
    cityCode?: string,
    stateName: string,
    stateCode?: string,
    address: string,
    pincode: number,
    locationName: string,
    locationCode?: string,
    id?: number,
    radius?: number,
    createdAt?: string,
    updatedAt?: string,
    country?: string,
    consigneeName?: string,
    consigneeCode?: string,
    locationType: string,
}