

class AsyncTaskExecutorEnvVariables(object):
    HTTP_HOST_NAME = "ASYNC_EXECUTOR_SUBSCRIPTION_HTTP_HOST"
    HTTP_URI = "ASYNC_EXECUTOR_SUBSCRIPTION_HTTP_URI"
    GRPC_HOST_NAME = "ASYNC_EXECUTOR_SUBSCRIPTION_GRPC_HOST"
    GRPC_TIMEOUT = "ASYNC_EXECUTOR_SUBSCRIPTION_GRPC_TIMEOUT"
    GRPC_PORT = "ASYNC_EXECUTOR_SUBSCRIPTION_GRPC_PORT"


class ServiceAccountEnvVariables(object):
    HOST = "SERVICE_ACCOUNT_HOST"
    PORT = "SERVICE_ACCOUNT_PORT"
    EMAIL = "SERVICE_ACCOUNT_EMAIL"


class RedisEnvVariables(object):
    HOST = "REDIS_HOST"
    PORT = "REDIS_PORT"
    DB = "REDIS_DB"


class JwtEnvVariables(object):
    CLIENT_SECRET = "JWT_CLIENT_SECRET"
    CLIENT_ID = "JWT_CLIENT_ID"
    API_IDENTIFIER = "JWT_API_IDENTIFIER"
    DOMAIN = "JWT_DOMAIN"


class AppEnvVariables(object):
    RAISE_EXCEPTION = "RAISE_EXCEPTION"
